- name: Dozzle
  community.docker.docker_container:
    name: dozzle
    image: amir20/dozzle
    state: started
    restart_policy: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: "true"

