---
- name: Create a directory if it does not exist
  become: true
  ansible.builtin.file:
    path: '{{ docker_config_dir }}/overseerr'
    state: directory
    owner: '{{ docker_uid }}'
    group: '{{ docker_gid }}'
  notify:
    - Restart overseerr

- include_role:
    name: docker_service
  vars:
    service_name: overseerr
    service_image: ghcr.io/sct/overseerr:1.32.4
    volumes:
      - '{{ docker_config_dir }}/overseerr:/app/config'
