---
- hosts: synologynas
  gather_facts: False
  roles:
    - traefik
    - glances
    - dozzle
    - syncthings
    - netbootxyz
    # Plex
    - plex
    # downloaders
    - nzbget
    - qbittorrent
    # Media Finders
    - bazarr
    - sonarr
    - radarr
- hosts: philcoulson
  gather_facts: False
  roles:
    - traefik
    - glances
    - dozzle
