---
- hosts: synologynas
  gather_facts: False
  roles:
    - role: autoheal
      tags: autoheal
    - role: traefik
      tags: traefik
    - role: glances
    - role: dozzle
    - role: syncthings
    - role: netbootxyz
    # debug
    - role: whoami
      tags: whoami
    # Plex
    - role: plex
      tags: plex
    # downloaders
    - role: nzbget
    - role: qbittorrent
    - role: blocky
      tags: blocky
    # Media Finders
    - role: overseerr
    - role: arrs
      vars:
        service_name: bazarr
        service_image: ghcr.io/k8s-at-home/bazarr:v1.1.2
    - role: arrs
      vars:
        service_name: sonarr
        service_image: ghcr.io/k8s-at-home/sonarr:v3.0.9.1549
    - role: arrs
      vars:
        service_name: radarr
        service_image: ghcr.io/k8s-at-home/radarr:v4.2.4.6635
    - role: arrs
      vars:
        service_name: lidarr
        service_image: ghcr.io/k8s-at-home/lidarr:v1.0.2.2592
    #- role: hotio
    #  vars:
    #    service_name: prowlarr
    #    service_image: hotio/prowlarr:release-1.2.2.2699@sha256:e358a68d6a354b45a38f05034471c44392f46788f94026fc090c1188168dff6f
    #  tags: prowlarr
    - role: arrs
      vars:
        service_name: readarr
        service_image: ghcr.io/k8s-at-home/readarr:v0.1.1.1352
    - role: linuxserver
      vars:
        service_name: calibre-web
        service_image: linuxserver/calibre-web:2021.12.16
        env:
          PUID: '1026'
          PGID: '100'
        volumes:
          - '{{media_base_dir}}/Books:/books'
    - role: linuxserver
      vars:
        service_name: heimdall
        service_image: linuxserver/heimdall:2.5.5
        #env:
        #  PUID: '1026'
        #  PGID: '100'
    - role: stash
      tags: stash
    - role: prometheus
      tags: prometheus
    - role: node-exporter
      tags: node-exporter
    - role: nut-exporter
      tags: nut-exporter
    - role: exportarr
      vars:
        services: "{{ exportarr_services }}"
      tags: exportarr

- hosts: thor
  gather_facts: False
  roles:
    - role: autoheal
    - role: blocky
      tags: blocky

#- name: Jenkins agents
#  import_playbook: jenkins_agents.yml
