---
- hosts: synologynas
  gather_facts: False
  roles:
    - role: autoheal
    - role: traefik
      tags: traefik
    - role: glances
    - role: dozzle
    - role: syncthings
    - role: netbootxyz
    # Plex
    - role: plex
    # downloaders
    - role: nzbget
    - role: qbittorrent
    - role: blocky
    # Media Finders
    - role: overseerr
    - role: arrs
      vars:
        service_name: bazarr
        service_image: ghcr.io/k8s-at-home/bazarr:v1.0.4
    - role: arrs
      vars:
        service_name: sonarr
        service_image: ghcr.io/k8s-at-home/sonarr:v3.0.8.1507
    - role: arrs
      vars:
        service_name: radarr
        service_image: ghcr.io/k8s-at-home/radarr:v4.1.0.6175
    - role: arrs
      vars:
        service_name: lidarr
        service_image: ghcr.io/k8s-at-home/lidarr:v1.0.0.2471
    - role: arrs
      vars:
        service_name: prowlarr
        service_image: ghcr.io/k8s-at-home/prowlarr:v0.4.0.1802
    - role: arrs
      vars:
        service_name: readarr
        service_image: ghcr.io/k8s-at-home/readarr:v0.1.1.1320
    - role: linuxserver
      vars:
        service_name: calibre-web
        service_image: linuxserver/calibre-web:version-0.6.19
        env:
          PUID: '1026'
          PGID: '100'
        volumes:
          - '{{media_base_dir}}/Books:/books'
    - role: stash

- hosts: thor
  gather_facts: False
  roles:
    - role: autoheal
    - role: blocky

#- name: Jenkins agents
#  import_playbook: jenkins_agents.yml
