---
- hosts: synologynas
  gather_facts: False
  roles:
    - role: glances
    - role: dozzle
    - role: syncthings
    # debug
    - role: whoami
      tags: whoami
    # Plex
    #- role: plex
    #  tags: plex
    # downloaders
    - role: nzbget
    - role: qbittorrent
      tags: qbittorrent
    # Media Finders
    - role: overseerr
    - role: arrs
      tags: arrs
      vars:
        service_name: bazarr
        service_image: "ghcr.io/onedr0p/bazarr:1.4.0"
        exposed_ports: [6767]
    - role: arrs
      tags: arrs
      vars:
        service_name: sonarr
        service_image: "ghcr.io/onedr0p/sonarr:3.0.10.1567"
        exposed_ports: [8989]
    - role: arrs
      tags: arrs
      vars:
        service_name: radarr
        service_image: "ghcr.io/onedr0p/radarr:5.2.6.8376"
        exposed_ports: [7878]
    - role: arrs
      tags: arrs
      vars:
        service_name: lidarr
        service_image: "ghcr.io/onedr0p/lidarr:1.4.5.3639"
        exposed_ports: [8686]
    - role: linuxserver
      vars:
        service_name: heimdall
        service_image: "linuxserver/heimdall:2.5.8"
        #env:
        #  PUID: '1026'
        #  PGID: '100'
    - role: stash
      tags: stash
    - role: node-exporter
      tags: node-exporter
    - role: nut-exporter
      tags: nut-exporter
    - role: exportarr
      vars:
        services: "{{ exportarr_services }}"
      tags: exportarr

#- name: Jenkins agents
#  import_playbook: jenkins_agents.yml
