---
- hosts: synologynas
  gather_facts: False
  roles:
    - role: autoheal
      tags: autoheal
    - role: traefik
      tags: traefik
    - role: glances
    - role: dozzle
    - role: syncthings
    - role: netbootxyz
      tags: netbootxyz
    # debug
    - role: whoami
      tags: whoami
    # Plex
    - role: plex
      tags: plex
    # downloaders
    - role: nzbget
    - role: qbittorrent
    - role: blocky
      tags: blocky
    # Media Finders
    - role: overseerr
    - role: arrs
      tags: arrs
      vars:
        service_name: bazarr
        service_image: "ghcr.io/onedr0p/bazarr:1.2.0"
        exposed_ports: [6767]
    - role: arrs
      tags: arrs
      vars:
        service_name: sonarr
        service_image: "ghcr.io/onedr0p/sonarr:3.0.10.1567"
        exposed_ports: [8989]
    - role: arrs
      tags: arrs
      vars:
        service_name: radarr
        service_image: "ghcr.io/onedr0p/radarr:4.4.4.7068"
        exposed_ports: [7878]
    - role: arrs
      tags: arrs
      vars:
        service_name: lidarr
        service_image: "ghcr.io/onedr0p/lidarr:1.1.4.3027"
        exposed_ports: [8686]
    - role: linuxserver
      vars:
        service_name: calibre-web
        service_image: "linuxserver/calibre-web:version-0.6.20"
        env:
          PUID: '1026'
          PGID: '100'
        volumes:
          - '{{media_base_dir}}/Books:/books'
    - role: linuxserver
      vars:
        service_name: heimdall
        service_image: "linuxserver/heimdall:2.5.6"
        #env:
        #  PUID: '1026'
        #  PGID: '100'
    - role: stash
      tags: stash
    - role: prometheus
      tags: prometheus
    - role: node-exporter
      tags: node-exporter
    - role: nut-exporter
      tags: nut-exporter
    - role: exportarr
      vars:
        services: "{{ exportarr_services }}"
      tags: exportarr

- hosts: thor
  gather_facts: False
  roles:
    - role: autoheal
    - role: blocky
      tags: blocky

#- name: Jenkins agents
#  import_playbook: jenkins_agents.yml
