---
ansible_host: 172.16.10.10
ansible_connection: ssh
ansible_ssh_user: halkeye
ansible_ssh_port: 4022
ansible_python_interpreter: /var/services/homes/halkeye/.python/./bin/python3


tailscale_hostname: ts.g4v.dev

docker_hostname: nas.g4v.dev
docker_config_dir: /volume1/docker
docker_data_dir: /volume1/Apps
docker_uid: 1026
docker_gid: 100

media_base_dir: /volume1

config_mode: '0775'

media_directories:
  - '{{ docker_data_dir }}/nzbget:/nzb-downloads'
  - '{{ docker_data_dir }}/torrents:/torrents'
  - '{{ media_base_dir }}/Anime:/anime'
  - '{{ media_base_dir }}/Anime Movies:/anime-movies'
  - '{{ media_base_dir }}/Audio/Audio Books:/audiobooks'
  - '{{ media_base_dir }}/Audio/Music:/music'
  - '{{ media_base_dir }}/Books:/books'
  - '{{ media_base_dir }}/Comedian Specials:/comedian-specials'
  - '{{ media_base_dir }}/Comics:/comics'
  - '{{ media_base_dir }}/Movies:/movies'
  - '{{ media_base_dir }}/TV:/tv'
  - '{{ media_base_dir }}/Webseries Movies:/webseries-movies'
  - '{{ media_base_dir }}/Webseries:/webseries'
