- name: netbootxyz
  community.docker.docker_container:
    name: netbootxyz
    image: "lscr.io/linuxserver/netbootxyz@sha256:d57891b3ff5b2ff937926383adf47bfd0629fa5e58845899d963a67f4be7005e"
    state: started
    env:
      PUID: "1000"
      PGID: "1000"
    volumes:
      - '{{ docker_config_dir }}/netbootxyz:/config'
      - '{{ docker_data_dir }}/netbootxyz:/assets'
    restart_policy: unless-stopped
    labels:
      traefik.enable: 'true'
      traefik.http.routers.netbootxyz.rule: 'Host(`netbootxyz.nas.g4v.dev`)'
      traefik.http.routers.netbootxyz.entrypoints: 'websecure'
      traefik.http.routers.netbootxyz.service: 'svc_netbootxyz'
      traefik.http.services.svc_netbootxyz.loadbalancer.server.port: '80'
      traefik.http.routers.netbootxyzadmin.rule: 'Host(`netbootxyz-admin.nas.g4v.dev`)'
      traefik.http.routers.netbootxyzadmin.entrypoints: 'websecure'
      traefik.http.routers.netbootxyzadmin.service: 'svc_netbootxyzadmin'
      traefik.http.services.svc_netbootxyzadmin.loadbalancer.server.port: '3000'
