---
- name: create jenkins-agent group
  group:
    name: '{{ jenkins_agent_username }}'
    state: present

- name: create jenkins-agent user
  user:
    name: jenkins-agent
    group: '{{ jenkins_agent_group }}'
    groups: 
      - '{{ jenkins_agent_group }}'
      - docker
    home: '{{ jenkins_agent_work_dir }}'
    shell: /sbin/nologin
    append: yes
    state: present
    create_home: yes
  notify:
    - Restart jenkins-agent

- name: Copy systemd service file to server
  template:
    src: jenkins-agent.service.j2
    dest: /etc/systemd/system/jenkins-agent.service
    owner: root
    group: root
  notify:
    - Restart jenkins-agent
