  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: '{{ docker_config_dir }}/radarr'
      state: directory
      mode: '0777'
      owner: '{{ docker_uid }}'
      group: '{{ docker_gid }}'
    notify:
      - Restart radarr

  - name: setup radarr specific volumes
    set_fact:
      radarr_config_volumes:
        - '{{ docker_config_dir }}/radarr:/config'

  - name: merge common and radarr volumes
    set_fact:
      radarr_volumes: "{{ media_directories + radarr_config_volumes }}"
    notify:
      - Restart radarr

  - name: radarr
    community.docker.docker_container:
      name: radarr
      image: ghcr.io/k8s-at-home/radarr:v4.0.4.5922
      user: '{{ docker_uid }}'
      env:
        TZ: "American/Vancouver"
      volumes: '{{ radarr_volumes }}'
      restart_policy: unless-stopped
      labels:
        traefik.enable: 'true'
