- name: Glances
  include_role:
    name: docker_service
  vars:
    service_name: glances
    service_image: nicolargo/glances
    pid_mode: host
    docker_user: ""
    docker_groups: []
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env:
      GLANCES_OPT: "-w"
    labels:
      traefik.enable: "true"
