- name: qbittorrent
  include_role:
    name: docker_service
  vars:
    service_name: qbittorrent
    service_image: guillaumedsde/alpine-qbittorrent-openvpn:latest
    docker_user: ""
    docker_groups: []
    volumes:
      - '{{ docker_config_dir }}/qbittorrent:/config'
      - '{{ docker_data_dir }}/torrents:/torrents'
    env:
      PUID: '{{ docker_uid | quote }}'
      PGID: '{{ docker_gid | quote }}'
      OPENVPN_PASSWORD: '{{ qbittorrent.openvpn.password }}'
      OPENVPN_USERNAME: '{{ qbittorrent.openvpn.username }}'
      OPENVPN_CONFIG: '{{ qbittorrent.openvpn.config }}'
      OPENVPN_PROVIDER: '{{ qbittorrent.openvpn.provider }}'
    capabilities:
      - NET_ADMIN
