- name: qbittorrent
  include_role:
    name: docker_service
  vars:
    service_name: qbittorrent
      # service_image: guillaumedsde/alpine-qbittorrent-openvpn@sha256:c26e53f3d1f2eb2503b442aa151ad80b044280b5bbd594c8bf95adac322187ce
    service_image:  lscr.io/linuxserver/qbittorrent@sha256:2b304d7f91ce15eaf91df168beddf63c063a66596e2dcb295708e94e33d61dfc
    docker_user: ""
    docker_groups: []
    volumes:
      - '{{ docker_config_dir }}/qbittorrent:/config'
      - '{{ docker_data_dir }}/torrents:/torrents'
    env:
      PUID: '{{ docker_uid | quote }}'
      PGID: '{{ docker_gid | quote }}'
      #OPENVPN_PASSWORD: '{{ qbittorrent.openvpn.password }}'
      #OPENVPN_USERNAME: '{{ qbittorrent.openvpn.username }}'
      #OPENVPN_CONFIG: '{{ qbittorrent.openvpn.config }}'
      #OPENVPN_PROVIDER: '{{ qbittorrent.openvpn.provider }}'
      #LAN: 172.16.10.0/24
    labels:
      autoheal: "true"
      "traefik.http.services.qbittorrent.loadbalancer.server.port": "8080"
    capabilities:
      - NET_ADMIN
    #healthcheck:
    #  test: ["CMD-SHELL", "healthcheck.sh"]
    #  interval: 1s
    #  retries: 3
    #  start_period: 10s
