---
# tasks file for docker_service
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: '{{ docker_config_dir }}/{{ service_name }}'
    state: directory
    mode: '{{ config_mode }}'
    owner: '{{ docker_uid }}'
    group: '{{ docker_gid }}'
  notify:
    - Restart {{ service_name }}

- name: Pull latest image
  community.docker.docker_image:
    name: '{{ service_image }}'
    source: pull
  notify:
    - Restart {{ service_name }}

- name: '{{ service_name }}'
  community.docker.docker_container:
    name: '{{ service_name }}'
    image: '{{ service_image }}'
    capabilities: '{{ capabilities }}'
    command: '{{ command | default(omit) }}'
    entrypoint: '{{ entrypoint | default(omit) }}'
    env: '{{ { "TZ": "America/Vancouver" } | combine(env) }}'
    groups: '{{ docker_groups }}'
    healthcheck: '{{ healthcheck | default({}) }}'
    labels: '{{ { "traefik.enable": "true" } | combine(labels) }}'
    networks: '{{ networks }}'
    pid_mode: '{{ pid_mode }}'
    ports: '{{ ports }}'
    restart_policy: unless-stopped
    user: '{{ docker_user }}'
    volumes: '{{ ["/etc/localtime:/etc/localtime:ro"] + volumes }}'
  notify:
    - Restart {{ service_name }}
