---
- name: Create a directory if it does not exist
  become: true
  ansible.builtin.file:
    path: '{{ docker_config_dir }}/blocky'
    state: directory
    owner: '{{ docker_uid }}'
    group: '{{ docker_gid }}'
  notify:
    - Restart blocky

- name: Copy config file
  become: true
  template:
    src: config.yml.j2
    dest: '{{docker_config_dir}}/blocky/config.yml'
    owner: '{{ docker_uid }}'
    group: '{{ docker_gid }}'
  notify:
    - Restart blocky

- include_role:
    name: docker_service
  vars:
    service_name: blocky
    service_image: spx01/blocky
    docker_user: "{{ docker_uid }}"
    docker_groups: ['{{ docker_gid }}']
    volumes:
        - '{{docker_config_dir}}/blocky/config.yml:/app/config.yml'
    ports:
        - 4000:4000
        - 53:53/udp
        - 53:53/tcp
    labels:
      "traefik.http.services.blocky.loadbalancer.server.port": "4000"
