---
- name: prometheus dir
  become: true
  ansible.builtin.file:
    path: '{{ docker_config_dir }}/prometheus'
    state: directory
    owner: '{{ docker_uid }}'
    group: '{{ docker_gid }}'
  notify:
    - Restart prometheus

- name: prometheus config dir
  become: true
  ansible.builtin.file:
    path: '{{ docker_config_dir }}/prometheus/config'
    state: directory
    owner: '{{ docker_uid }}'
    group: '{{ docker_gid }}'
  notify:
    - Restart prometheus

- name: Copy prometheus.yml file
  become: true
  template:
    src: prometheus.yml.j2
    dest: '{{docker_config_dir}}/prometheus/config/prometheus.yml'
    owner: '{{ docker_uid }}'
    group: '{{ docker_gid }}'
  notify:
    - Restart prometheus

#- name: prometheus rules dir
#  become: true
#  ansible.builtin.file:
#    path: '{{ docker_config_dir }}/prometheus/rules'
#    state: directory
#    owner: '{{ docker_uid }}'
#    group: '{{ docker_gid }}'
#  notify:
#    - Restart prometheus

- name: prometheus data dir
  become: true
  ansible.builtin.file:
    path: '{{ docker_data_dir }}/prometheus'
    state: directory
    owner: '{{ docker_uid }}'
    group: '{{ docker_gid }}'
  notify:
    - Restart prometheus

- include_role:
    name: docker_service
  vars:
    service_name: prometheus
    service_image: quay.io/prometheus/prometheus:v2.47.0
    docker_user: "{{ docker_uid }}"
    docker_groups:
      - "{{ docker_gid }}"
    volumes:
      - '{{ docker_config_dir }}/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml'
      #- '{{ docker_config_dir }}/prometheus/rules:/etc/prometheus/rules'
      - '{{ docker_data_dir }}/prometheus:/storage'
    command:
      - "--web.enable-lifecycle"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/storage"
