---
# defaults file for docker_service
config_path: /config
env: {}
labels: {}
docker_user: '{{ docker_uid }}'
docker_groups: ['{{ docker_gid }}']
networks: []
pid_mode: ""
ports: []
service_image: ' missing service image'
service_name: 'missing service name'
capabilities: []
default_host_ip: ""
