- name: plex
  community.docker.docker_container:
    name: plex
    state: started
    image: plexinc/pms-docker:1.30.2.6563-3d4dc0cce
    pull: yes
    network_mode: host
    env:
      TZ: "America/Vancouver"
      PLEX_CLAIM: '{{ plex_claim }}'
      CHANGE_CONFIG_DIR_OWNERSHIP: "false"
    volumes:
      - '{{docker_config_dir}}/plex:/config'
      - '{{docker_data_dir}}/plex:/transcode'
      - /volume1/Anime Movies:/volume1/Anime Movies
      - /volume1/Anime:/volume1/Anime
      - /volume1/Audio/Audio Books:/volume1/Audio/Audio Books
      - /volume1/Audio/Comedians:/volume1/Audio/Comedians
      - /volume1/Audio/Music:/volume1/Audio/Music
      - /volume1/Comedian Specials:/volume1/Comedian Specials
      - /volume1/Movies:/volume1/Movies
      - /volume1/TV:/volume1/TV
      - /volume1/Webseries Movies:/volume1/Webseries Movies
      - /volume1/Webseries:/volume1/Webseries
    restart_policy: unless-stopped
    labels:
      traefik.enable: "false"
