- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: '{{ docker_config_dir }}/bazarr'
    state: directory
    mode: '0755'

- set_fact:
    bazarr_config_volumes:
      - '{{ docker_config_dir }}/bazarr:/config'

- set_fact:
    bazarr_volumes: "{{ media_directories + bazarr_config_volumes }}"

- name: bazarr
  community.docker.docker_container:
    name: bazarr
    image: linuxserver/bazarr:version-v1.0.3
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "American/Vancouver"
    volumes: '{{ bazarr_volumes }}'
    restart_policy: unless-stopped
    labels:
      traefik.enable: 'true'

