- name: nzbget
  community.docker.docker_container:
    name: nzbget
    image: amir20/dozzle
    state: started
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: "true"

