- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: '{{ docker_config_dir }}/{{ service_name }}'
    state: directory
    mode: '0777'
    owner: '{{ docker_uid }}'
    group: '{{ docker_gid }}'
  notify:
    - Restart {{ service_name }}

- name: create volumes variable
  set_fact:
    builtin_volumes:
      - '{{ docker_config_dir }}/{{ service_name }}:/config'

- name: '{{ service_name }}'
  community.docker.docker_container:
    name: '{{ service_name }}'
    image: '{{ service_image }}'
    env: '{{ { "TZ": "America/Vancouver", "PUID": "{{docker_uid}}", "GUID": "{{docker_gid}}" } | combine(env) }}'
    volumes: "{{ builtin_volumes + volumes }}"
    restart_policy: unless-stopped
    labels: '{{ { "traefik.enable": "true" } | combine(labels) }}'

